spring:
  main:
    lazy-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/bank?useUnicode=yes&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: bank
    password: Bank@123
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update